name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build_native:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build release target
      run: cargo build --release

  build-gem:
    needs:  build_native
    strategy:
      matrix:
        # ruby: ["3.0", "3.1", "3.2", "3.3", "head"]
        ruby: ["3.1"]
        # runs-on: ["ubuntu-latest", "macos-13", "windows-latest"]
        runs-on: ["ubuntu-latest", "macos-13"]
    runs-on: ${{matrix.runs-on}}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby-pkgs@v1
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true
          # mingw: "libyaml" # windows
          apt-get: "libyaml-dev" # linux
          brew: "libyaml" # macos

      - run: bundle install && bundle exec rake compile
  
  rubocop:
    needs: [build_native, build-gem]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true
      - run: bundle exec rake rubocop

  # valgrind:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ruby/setup-ruby-pkgs@v1
  #       with:
  #         ruby-version: "3.3"
  #         bundler-cache: true
  #         apt-get: valgrind
  #     - uses: actions/cache@v4
  #       with:
  #         path: ports
  #         key: ports-ubuntu-${{ hashFiles('ext/libsql/extconf.rb') }}
  #     - run: bundle exec rake compile
#      - run: bundle exec rake test:valgrind

  # cruby-package:
  #   runs-on: "ubuntu-latest"
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/cache@v4
  #       with:
  #         path: precompiled/ports/archives
  #         key: archives-ubuntu-${{hashFiles('precompiled/ext/precompiled/extconf.rb')}}
  #     - uses: ruby/setup-ruby@v1
  #       with:
  #         working-directory: precompiled
  #         ruby-version: "3.2"
  #         bundler-cache: true
  #     - run: ./bin/test-gem-build gems ruby
  #       working-directory: precompiled
  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: cruby-gem
  #         path: precompiled/gems
  #         retention-days: 1
