name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1.0'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rake

  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true
      - run: bundle exec rake rubocop

  valgrind:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby-pkgs@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
          apt-get: valgrind
      - uses: actions/cache@v4
        with:
          path: ports
          key: ports-ubuntu-${{ hashFiles('ext/libsql/extconf.rb') }}
      - run: bundle exec rake compile
      - run: bundle exec rake test:valgrind
